#持久层配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lu_tale?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root

#日志文件
logging:
  level:
    root: warn
    com.tasty: info
  file:
    name: log/blog-pro.log